# Generated by Django 4.1.3 on 2022-11-22 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('Brand_deiscription', models.CharField(default=None, max_length=500)),
                ('Brand_Logo', models.ImageField(default=None, upload_to='media/Brand')),
                ('Status', models.CharField(choices=[('ACTIVE', 'Active'), ('HIDE', 'Hide')], default=1, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('Status', models.CharField(choices=[('ACTIVE', 'Active'), ('HIDE', 'Hide')], default=1, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CityName', models.CharField(max_length=100)),
                ('Status', models.CharField(choices=[('ACTIVE', 'Active'), ('HIDE', 'Hide')], default=1, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountryName', models.CharField(max_length=100)),
                ('Status', models.CharField(choices=[('ACTIVE', 'Active'), ('HIDE', 'Hide')], default=1, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discount_value', models.IntegerField(default=0)),
                ('Discount_type', models.CharField(max_length=20)),
                ('Status', models.CharField(choices=[('ACTIVE', 'Active'), ('HIDE', 'Hide')], default=1, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StrainType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strain', models.CharField(choices=[('N', 'None'), ('i', 'Indica'), ('s', 'Sativa'), ('h', 'hybrid'), ('c', 'CBD')], max_length=50)),
                ('Status', models.CharField(choices=[('ACTIVE', 'Active'), ('HIDE', 'Hide')], default=1, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='taxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_value', models.IntegerField(default=0)),
                ('tax_type', models.CharField(max_length=20)),
                ('Status', models.CharField(choices=[('ACTIVE', 'Active'), ('HIDE', 'Hide')], default=1, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('Status', models.CharField(choices=[('ACTIVE', 'Active'), ('HIDE', 'Hide')], default=1, max_length=20)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.category')),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StateName', models.CharField(max_length=100)),
                ('Status', models.CharField(choices=[('ACTIVE', 'Active'), ('HIDE', 'Hide')], default=1, max_length=20)),
                ('CountryName', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.countries')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Product_Name', models.CharField(max_length=100, unique=True)),
                ('Product_Details', models.CharField(default=None, max_length=150)),
                ('SKU', models.CharField(max_length=100)),
                ('Product_Image', models.ImageField(default=None, upload_to='media/Products')),
                ('Multiple_Image', models.FileField(default=None, null=True, upload_to='media/Products/MultipleImages')),
                ('Product_Video', models.FileField(null=True, upload_to='media/Videos')),
                ('quantity', models.IntegerField(default=1)),
                ('UPC', models.CharField(max_length=100)),
                ('prices', models.IntegerField(blank=True, default=1, null=True)),
                ('AlloW_tax', models.BooleanField(default=True)),
                ('Allow_discount', models.BooleanField(default=False)),
                ('net_weight', models.CharField(choices=[('1g', '1g'), ('1/8 oz', '1/8 oz'), ('1/4 oz', '1/4 oz'), ('1/2 oz', '1/2 oz'), ('1 oz', '1 oz'), ('pre-roll 0.5g', 'pre-roll 0.5g')], default=None, max_length=50)),
                ('Description', models.CharField(default=None, max_length=500)),
                ('THC', models.IntegerField(blank=True, default=0)),
                ('CBD', models.IntegerField(blank=True, default=0)),
                ('CBN', models.IntegerField(blank=True, default=0)),
                ('lab_Result', models.CharField(choices=[('percentage', '%'), ('Magnesium', 'Mg')], max_length=50)),
                ('tag', models.CharField(blank=True, default=None, max_length=50)),
                ('Stock', models.CharField(choices=[('In Stock', 'IN STOCK'), ('Out of Stock', 'OUT OF STOCK')], default=1, max_length=20)),
                ('Status', models.CharField(choices=[('ACTIVE', 'Active'), ('HIDE', 'Hide')], default=1, max_length=20)),
                ('DiscountedAmount', models.IntegerField(blank=True, null=True)),
                ('taxedAmount', models.IntegerField(blank=True, null=True)),
                ('Alt_Text', models.CharField(default=None, max_length=50)),
                ('Brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.brand')),
                ('Category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.category')),
                ('City', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.cities')),
                ('Country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.countries')),
                ('State', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.states')),
                ('Strain_Types', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.straintype')),
                ('Sub_Category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.subcategory')),
                ('discount', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.discount')),
                ('tax', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.taxes')),
            ],
        ),
        migrations.AddField(
            model_name='cities',
            name='StatesName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.states'),
        ),
    ]
