# Generated by Django 4.1.4 on 2022-12-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminPanel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="createdMonth",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
