# Generated by Django 4.1.3 on 2022-12-02 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimGiftVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Flavours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavour_Name', models.CharField(default=None, max_length=50)),
                ('Price', models.IntegerField(default=0)),
                ('FlavoursImage', models.ImageField(default=None, upload_to='media/Products')),
            ],
        ),
        migrations.CreateModel(
            name='GiftVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Net_Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Weight_type', models.CharField(default=None, max_length=50)),
                ('Weight_size', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Weight_Price', models.IntegerField(default=0)),
                ('Status', models.CharField(choices=[('1', 'Active'), ('0', 'Hide')], default=1, max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='SubCategory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.subcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Claimed_Coupoun',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.claimedcoupon'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.taxes'),
        ),
        migrations.AddField(
            model_name='product',
            name='GiftVoucher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.claimgiftvoucher'),
        ),
        migrations.AddField(
            model_name='product',
            name='flavour',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.flavours'),
        ),
        migrations.AlterField(
            model_name='product',
            name='net_weight',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.net_weight'),
        ),
    ]
