# Generated by Django 4.1.4 on 2022-12-21 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AdminPanel", "0002_product_createdmonth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="createdMonth",
        ),
    ]
