# Generated by Django 4.1.3 on 2022-11-09 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0002_registeruser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeruser',
            old_name='username',
            new_name='Username',
        ),
    ]
