# Generated by Django 4.1.3 on 2022-11-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0003_rename_username_registeruser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeruser',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.AddField(
            model_name='registeruser',
            name='password',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
