# Generated by Django 4.1.3 on 2022-12-02 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0003_claimgiftvoucher_giftvoucher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimgiftvoucher',
            name='GiftVoucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.coupon'),
        ),
    ]
