# Generated by Django 4.1.3 on 2022-11-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0004_rename_gender_registeruser_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(choices=[('india', 'INDIA'), ('united states of america', 'UNITED STATES OF AMERICA')], max_length=100)),
            ],
        ),
    ]
