# Generated by Django 4.1.3 on 2022-12-02 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0004_alter_claimgiftvoucher_giftvoucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimgiftvoucher',
            name='GiftVoucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.giftvoucher'),
        ),
        migrations.AlterField(
            model_name='giftvoucher',
            name='code',
            field=models.CharField(blank=True, default=' ', max_length=8, null=True, unique=True),
        ),
    ]
