# Generated by Django 4.1.3 on 2022-11-10 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0005_country'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='Countries',
        ),
    ]
