# Generated by Django 4.1.3 on 2022-12-02 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0006_alter_giftvoucher_code_alter_net_weight_weight_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='net_weight',
            name='Weight_size',
        ),
    ]
