# Generated by Django 4.1.3 on 2022-11-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0006_rename_country_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='Country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='Gender',
            field=models.CharField(max_length=20),
        ),
    ]
