# Generated by Django 4.1.3 on 2022-12-03 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0007_remove_net_weight_weight_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.taxes'),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='tax_value',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
