# Generated by Django 4.1.3 on 2022-12-03 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0008_alter_product_tax_alter_taxes_tax_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.taxes'),
        ),
    ]
