# Generated by Django 4.1.3 on 2022-12-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0010_alter_product_sku_alter_product_upc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftvoucher',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
