# Generated by Django 4.1.3 on 2022-11-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0011_straintype'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('THC', models.IntegerField(blank=True, choices=[('percentage', '%'), ('Magnesium', 'Mg')], null=True)),
                ('CBD', models.IntegerField(blank=True, choices=[('percentage', '%'), ('Magnesium', 'Mg')], null=True)),
                ('CBN', models.IntegerField(blank=True, choices=[('percentage', '%'), ('Magnesium', 'Mg')], null=True)),
            ],
        ),
    ]
