# Generated by Django 4.1.3 on 2022-11-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0012_labresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labresults',
            name='CBD',
            field=models.CharField(choices=[('percentage', '%'), ('Magnesium', 'Mg')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='labresults',
            name='CBN',
            field=models.CharField(choices=[('percentage', '%'), ('Magnesium', 'Mg')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='labresults',
            name='THC',
            field=models.CharField(choices=[('percentage', '%'), ('Magnesium', 'Mg')], default=1, max_length=10),
        ),
    ]
