# Generated by Django 4.1.3 on 2022-11-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0014_alter_labresults_cbd_alter_labresults_cbn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresults',
            name='CBD_Size',
            field=models.CharField(choices=[(' ', ' '), ('percentage', '%'), ('Magnesium', 'Mg')], default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='labresults',
            name='CBN_Size',
            field=models.CharField(choices=[(' ', ' '), ('percentage', '%'), ('Magnesium', 'Mg')], default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='labresults',
            name='THC_Size',
            field=models.CharField(choices=[(' ', ' '), ('percentage', '%'), ('Magnesium', 'Mg')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='labresults',
            name='CBD',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='labresults',
            name='CBN',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='labresults',
            name='THC',
            field=models.IntegerField(default=1),
        ),
    ]
