# Generated by Django 4.1.3 on 2022-11-10 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0015_labresults_cbd_size_labresults_cbn_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=50)),
                ('Brand_deiscription', models.CharField(default=1, max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='labresults',
            name='CBD_Size',
            field=models.CharField(choices=[('percentage', '%'), ('Magnesium', 'Mg')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='labresults',
            name='CBN_Size',
            field=models.CharField(choices=[('percentage', '%'), ('Magnesium', 'Mg')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='labresults',
            name='THC_Size',
            field=models.CharField(choices=[('percentage', '%'), ('Magnesium', 'Mg')], default=1, max_length=10),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=100)),
                ('SKU', models.CharField(max_length=100)),
                ('UPC', models.CharField(max_length=100)),
                ('prices', models.IntegerField(default=1)),
                ('net_weight', models.CharField(choices=[('1g', '1g'), ('1/8 oz', '1/8 oz'), ('1/4 oz', '1/4 oz'), ('1/2 oz', '1/2 oz'), ('1 oz', '1 oz'), ('pre-roll 0.5g', 'pre-roll 0.5g')], default=None, max_length=50)),
                ('ProductDetails', models.CharField(default=1, max_length=150)),
                ('Description', models.CharField(default=1, max_length=500)),
                ('tag', models.CharField(default=None, max_length=50)),
                ('discount', models.IntegerField(default=None)),
                ('Brand', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.brand')),
                ('Category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.subcategory')),
                ('Strain_Types', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.straintype')),
                ('lab_Result', models.ForeignKey(choices=[('percentage', '%'), ('Magnesium', 'Mg')], on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.labresults')),
            ],
        ),
    ]
