# Generated by Django 4.1.3 on 2022-11-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0016_brand_alter_labresults_cbd_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ProductName',
            new_name='Product_Name',
        ),
        migrations.RemoveField(
            model_name='labresults',
            name='CBD_Size',
        ),
        migrations.RemoveField(
            model_name='labresults',
            name='CBN_Size',
        ),
        migrations.RemoveField(
            model_name='labresults',
            name='THC_Size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ProductDetails',
        ),
        migrations.AddField(
            model_name='brand',
            name='Brand_Logo',
            field=models.ImageField(default=None, upload_to='media/Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Details',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Image',
            field=models.ImageField(default=None, upload_to='media/Products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
