# Generated by Django 4.1.3 on 2022-11-10 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0018_alter_brand_brand_deiscription_alter_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Sub_Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.subcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.category'),
        ),
    ]
