# Generated by Django 4.1.3 on 2022-11-10 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0020_product_city_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.countries'),
        ),
        migrations.AddField(
            model_name='product',
            name='State',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.states'),
        ),
    ]
